#pragma once
#include <vector>
#include <string>
#include <set>
#include <cmath>
#include <thread>
#include <allegro5/allegro.h>
#include <allegro5/color.h>
#include <allegro5/allegro_primitives.h>
#include <allegro5/allegro_primitives.h>
#include <allegro5/allegro_image.h>
#include <allegro5/allegro_font.h>
#include <allegro5/allegro_ttf.h>